#requires -Version 5.1
<#
ez-gdal Windows プラグイン正式サポート準備フェーズの PoC スクリプト。
GDAL 公式 release tarball から、プラグイン作成に必要なヘッダのみを
抽出する。

なぜ自前抽出が必要か:
- MaxRev.Gdal.WindowsRuntime.Minimal には gdal.dll のみで .h が同梱されない
- プラグイン作者が ezgdal 内蔵 GDAL とまったく同じ minor (3.12.x) に
  対してビルドするには、同 patch のソースから取ったヘッダを参照させたい
  (Homebrew/vcpkg/apt の host gdal は patch がずれる可能性がある)

PoC スコープ:
- 取得対象は port/ gcore/ alg/ ogr/ ogr/ogrsf_frmts/ の .h を平坦化コピー
- 内部ヘッダ (*_p.h) は除外
- gdal_version.h は configure 生成のため別途生成 (テンプレートを補完)
#>

[CmdletBinding()]
param(
    # MaxRev WindowsRuntime 3.12.3.499 の upstream GDAL バージョンに揃える
    # (本セッションで nuspec を確認済み: GDAL 3.12.3)
    [string]$Version = "3.12.3",
    [string]$OutDir  = (Join-Path $PSScriptRoot "build")
)

$ErrorActionPreference = "Stop"

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$tarPath     = Join-Path $OutDir "gdal-$Version.tar.gz"
$extractRoot = Join-Path $OutDir "src"
$srcDir      = Join-Path $extractRoot "gdal-$Version"
$includeDir  = Join-Path $OutDir "include\gdal"

if (-not (Test-Path -LiteralPath $tarPath)) {
    $url = "https://github.com/OSGeo/gdal/releases/download/v$Version/gdal-$Version.tar.gz"
    Write-Host "[1/3] download $url"
    # GitHub releases へのアクセスに最低 TLS 1.2 が要る環境があるため明示。
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $url -OutFile $tarPath -UseBasicParsing
} else {
    Write-Host "[1/3] cached $tarPath"
}

if (-not (Test-Path -LiteralPath $srcDir)) {
    Write-Host "[2/3] extract -> $extractRoot"
    New-Item -ItemType Directory -Force -Path $extractRoot | Out-Null
    # Windows 10 1803+ / Server 2019+ は標準 tar (bsdtar) が C:\Windows\System32\tar.exe にある。
    & tar.exe -xzf $tarPath -C $extractRoot
    if ($LASTEXITCODE -ne 0) { throw "tar -xzf failed (exit $LASTEXITCODE)" }
} else {
    Write-Host "[2/3] cached $srcDir"
}

Write-Host "[3/3] flatten public headers -> $includeDir"
if (Test-Path -LiteralPath $includeDir) {
    Remove-Item -LiteralPath $includeDir -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $includeDir | Out-Null

# プラグイン公開 API として必要なディレクトリ。internal (_p.h) は除外する。
# Phase 2 で SDK nupkg 化する際、このリストが SDK の include スコープになる。
$publicDirs = @("port", "gcore", "alg", "ogr", "ogr\ogrsf_frmts", "frmts")
$copied = 0
foreach ($d in $publicDirs) {
    $abs = Join-Path $srcDir $d
    if (-not (Test-Path -LiteralPath $abs)) {
        Write-Warning "  skipped (not found): $d"
        continue
    }
    Get-ChildItem -LiteralPath $abs -Filter "*.h" -File | Where-Object {
        # GDAL の慣習で _p.h サフィックスは internal header
        $_.Name -notlike "*_p.h"
    } | ForEach-Object {
        Copy-Item $_.FullName -Destination $includeDir -Force
        $copied++
    }
}

# gdal_version.h は CMake configure で gdal_version.h.in から生成される。
# release tarball にも本物の .h は含まれていない可能性が高いので、最小版
# を組み立てる (Major/Minor/Rev のみ)。プラグインで version 比較が必要な
# ケースに最低限対応するため。-Version を変えて再実行したときに古い値が
# 残らないよう、毎回上書きする。
$v = [version]$Version
$verNum = ($v.Major * 1000000) + ($v.Minor * 10000) + ($v.Build * 100)
$gdalVersion = @"
/* generated by scripts/win-sdk/fetch-gdal-headers.ps1 (PoC, minimal) */
#ifndef GDAL_VERSION_H_INCLUDED
#define GDAL_VERSION_H_INCLUDED
#define GDAL_VERSION_MAJOR $($v.Major)
#define GDAL_VERSION_MINOR $($v.Minor)
#define GDAL_VERSION_REV   $($v.Build)
#define GDAL_VERSION_BUILD 0
#define GDAL_VERSION_NUM   $verNum
#define GDAL_RELEASE_NAME  "$Version"
#endif
"@
$genPath = Join-Path $includeDir "gdal_version.h"
Set-Content -Encoding ASCII -LiteralPath $genPath -Value $gdalVersion
$copied++
Write-Host "  generated: gdal_version.h (PoC minimal)"

Write-Host ""
Write-Host "OK: $includeDir ($copied headers)"
Write-Host "Use with: cl /I `"$includeDir`" plugin.cpp"
